
from mysql:5
ENV MYSQL_ROOT_PASSWORD=mysql
ENV MYSQL_DATABASE=mybooks

expose 3306

COPY init_db.sql /docker-entrypoint-initdb.d/

RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/
RUN chown -R mysql:mysql /var/lib/mysql
RUN chgrp -R mysql /var/lib/mysql
RUN chmod 755 /var/lib/mysql