version: "3"
services:
  db:
    image: muguirajames/db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=magoo
      - MYSQL_PASSWORD=mysql
    volumes:
      - "data:/var/lib/mysql"
      
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "3306:3306"
    networks:
      - webnet
  web:
    # replace username/repo:tag with your name and image details
    image: muguirajames/nodee
    depends_on:
      - db
    entrypoint: ./wait-for-it.sh db:3306  -- node server.js
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - webnet
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8888:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   networks:
  #     - webnet
 
volumes:
  data:
networks:
  webnet:
